context("simulate_site_data")

test_that("simulate_site_data", {
  # data
  d <- simulate_site_data(n_sites = 1000, n_features = 5, prop = 0.5)
  # tests
  expect_is(d, "sf")
  expect_equal(nrow(d), 1000)
  expect_is(d$f1, "numeric")
  expect_true(any(is.finite(d$f1)))
  expect_true(any(!is.finite(d$f1)))
  expect_is(d$f2, "numeric")
  expect_true(any(is.finite(d$f2)))
  expect_true(any(!is.finite(d$f2)))
  expect_is(d$f3, "numeric")
  expect_true(any(is.finite(d$f3)))
  expect_true(any(!is.finite(d$f3)))
  expect_is(d$p1, "numeric")
  expect_true(all(is.finite(d$p1)))
  expect_true(all(d$p1 >= 0))
  expect_true(all(d$p1 <= 1))
  expect_is(d$p2, "numeric")
  expect_true(all(is.finite(d$p2)))
  expect_true(all(d$p2 >= 0))
  expect_true(all(d$p2 <= 1))
  expect_is(d$p3, "numeric")
  expect_true(all(is.finite(d$p3)))
  expect_true(all(d$p3 >= 0))
  expect_true(all(d$p3 <= 1))
  expect_is(d$e1, "numeric")
  expect_true(all(is.finite(d$e1)))
  expect_is(d$e2, "numeric")
  expect_true(all(is.finite(d$e2)))
  expect_is(d$survey_cost, "numeric")
  expect_true(all(is.finite(d$survey_cost)))
  expect_true(all(d$survey_cost >= 0))
  expect_is(d$management_cost, "numeric")
  expect_true(all(is.finite(d$management_cost)))
  expect_true(all(d$management_cost >= 0))
})
