# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_standard_error_value <- function(x) {
    .Call(`_surveyvoi_rcpp_standard_error_value`, x)
}

rcpp_log_sum <- function(x) {
    .Call(`_surveyvoi_rcpp_log_sum`, x)
}

rcpp_approx_expected_value_of_decision_given_survey_scheme <- function(pij, survey_features, survey_sensitivity, survey_specificity, pu_survey_solution, pu_survey_costs, pu_purchase_costs, pu_purchase_locked_in, pu_purchase_locked_out, obj_fun_target, total_budget, n_approx_replicates, n_approx_outcomes_per_replicate, method_approx_outcomes, seed) {
    .Call(`_surveyvoi_rcpp_approx_expected_value_of_decision_given_survey_scheme`, pij, survey_features, survey_sensitivity, survey_specificity, pu_survey_solution, pu_survey_costs, pu_purchase_costs, pu_purchase_locked_in, pu_purchase_locked_out, obj_fun_target, total_budget, n_approx_replicates, n_approx_outcomes_per_replicate, method_approx_outcomes, seed)
}

rcpp_expected_value_of_action <- function(solution, pij, target) {
    .Call(`_surveyvoi_rcpp_expected_value_of_action`, solution, pij, target)
}

rcpp_expected_value_of_decision_given_current_info <- function(pij, pu_costs, pu_locked_in, pu_locked_out, target, budget) {
    .Call(`_surveyvoi_rcpp_expected_value_of_decision_given_current_info`, pij, pu_costs, pu_locked_in, pu_locked_out, target, budget)
}

rcpp_expected_value_of_decision_given_survey_scheme <- function(pij, survey_features, survey_sensitivity, survey_specificity, pu_survey_solution, pu_survey_costs, pu_purchase_costs, pu_purchase_locked_in, pu_purchase_locked_out, obj_fun_target, total_budget) {
    .Call(`_surveyvoi_rcpp_expected_value_of_decision_given_survey_scheme`, pij, survey_features, survey_sensitivity, survey_specificity, pu_survey_solution, pu_survey_costs, pu_purchase_costs, pu_purchase_locked_in, pu_purchase_locked_out, obj_fun_target, total_budget)
}

rcpp_feasible_actions_ilp_matrix <- function(x) {
    .Call(`_surveyvoi_rcpp_feasible_actions_ilp_matrix`, x)
}

rcpp_greedy_heuristic_prioritization <- function(rij, pu_costs, pu_locked_in, pu_locked_out, target, budget) {
    .Call(`_surveyvoi_rcpp_greedy_heuristic_prioritization`, rij, pu_costs, pu_locked_in, pu_locked_out, target, budget)
}

rcpp_model_performance <- function(y, yhat, w, data_sens, data_spec) {
    .Call(`_surveyvoi_rcpp_model_performance`, y, yhat, w, data_sens, data_spec)
}

rcpp_formula_sensitivity_and_specificity <- function(x, data_sens, data_spec) {
    .Call(`_surveyvoi_rcpp_formula_sensitivity_and_specificity`, x, data_sens, data_spec)
}

rcpp_maxlik_sensitivity_and_specificity <- function(x, data_sens, data_spec) {
    .Call(`_surveyvoi_rcpp_maxlik_sensitivity_and_specificity`, x, data_sens, data_spec)
}

rcpp_pmedian_constraint_matrix <- function(x, costs) {
    .Call(`_surveyvoi_rcpp_pmedian_constraint_matrix`, x, costs)
}

rcpp_total_probability_of_positive_result <- function(prior, sensitivity, specificity) {
    .Call(`_surveyvoi_rcpp_total_probability_of_positive_result`, prior, sensitivity, specificity)
}

rcpp_total_probability_of_negative_result <- function(prior, sensitivity, specificity) {
    .Call(`_surveyvoi_rcpp_total_probability_of_negative_result`, prior, sensitivity, specificity)
}

rcpp_probability_of_outcome <- function(oij, total_probability_of_survey_positive, total_probability_of_survey_negative, idx) {
    .Call(`_surveyvoi_rcpp_probability_of_outcome`, oij, total_probability_of_survey_positive, total_probability_of_survey_negative, idx)
}

rcpp_probability_of_state <- function(sij, pij) {
    .Call(`_surveyvoi_rcpp_probability_of_state`, sij, pij)
}

rcpp_sample_n_weighted_states_with_replacement <- function(k, pij, seed) {
    .Call(`_surveyvoi_rcpp_sample_n_weighted_states_with_replacement`, k, pij, seed)
}

rcpp_sample_n_uniform_states_with_replacement <- function(k, pij, seed) {
    .Call(`_surveyvoi_rcpp_sample_n_uniform_states_with_replacement`, k, pij, seed)
}

rcpp_sample_n_uniform_states_without_replacement <- function(k, pij, seed) {
    .Call(`_surveyvoi_rcpp_sample_n_uniform_states_without_replacement`, k, pij, seed)
}

rcpp_sample_n_weighted_states_without_replacement <- function(k, pij, seed) {
    .Call(`_surveyvoi_rcpp_sample_n_weighted_states_without_replacement`, k, pij, seed)
}

rcpp_nth_state_sparse <- function(n, idx, matrix) {
    .Call(`_surveyvoi_rcpp_nth_state_sparse`, n, idx, matrix)
}

rcpp_nth_state <- function(n, matrix) {
    .Call(`_surveyvoi_rcpp_nth_state`, n, matrix)
}

rcpp_n_states <- function(n) {
    .Call(`_surveyvoi_rcpp_n_states`, n)
}

rcpp_which_state_sparse <- function(matrix, idx) {
    .Call(`_surveyvoi_rcpp_which_state_sparse`, matrix, idx)
}

rcpp_which_state <- function(matrix) {
    .Call(`_surveyvoi_rcpp_which_state`, matrix)
}

rcpp_update_posterior_probability_matrix <- function(pij, oij, survey_features, survey_sensitivity, survey_specificity, pu_survey_solution) {
    .Call(`_surveyvoi_rcpp_update_posterior_probability_matrix`, pij, oij, survey_features, survey_sensitivity, survey_specificity, pu_survey_solution)
}

