# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_standard_error_value <- function(x) {
    .Call(`_surveyvoi_rcpp_standard_error_value`, x)
}

rcpp_log_sum <- function(x) {
    .Call(`_surveyvoi_rcpp_log_sum`, x)
}

rcpp_approx_expected_value_of_action <- function(solution, pij, alpha, gamma, states) {
    .Call(`_surveyvoi_rcpp_approx_expected_value_of_action`, solution, pij, alpha, gamma, states)
}

rcpp_approx_expected_value_of_decision_given_current_info_n_states <- function(pij, pu_costs, pu_locked_in, alpha, gamma, n_approx_obj_fun_points, budget, gap, n_approx_replicates, n_approx_states_per_replicate) {
    .Call(`_surveyvoi_rcpp_approx_expected_value_of_decision_given_current_info_n_states`, pij, pu_costs, pu_locked_in, alpha, gamma, n_approx_obj_fun_points, budget, gap, n_approx_replicates, n_approx_states_per_replicate)
}

rcpp_approx_expected_value_of_decision_given_current_info_fixed_states <- function(pij, pu_costs, pu_locked_in, alpha, gamma, n_approx_obj_fun_points, budget, gap, states) {
    .Call(`_surveyvoi_rcpp_approx_expected_value_of_decision_given_current_info_fixed_states`, pij, pu_costs, pu_locked_in, alpha, gamma, n_approx_obj_fun_points, budget, gap, states)
}

rcpp_approx_expected_value_of_decision_given_perfect_info_n_states <- function(pij, pu_costs, pu_locked_in, alpha, gamma, n_approx_obj_fun_points, budget, gap, n_approx_replicates, n_approx_states_per_replicate) {
    .Call(`_surveyvoi_rcpp_approx_expected_value_of_decision_given_perfect_info_n_states`, pij, pu_costs, pu_locked_in, alpha, gamma, n_approx_obj_fun_points, budget, gap, n_approx_replicates, n_approx_states_per_replicate)
}

rcpp_approx_expected_value_of_decision_given_perfect_info_fixed_states <- function(pij, pu_costs, pu_locked_in, alpha, gamma, n_approx_obj_fun_points, budget, gap, states) {
    .Call(`_surveyvoi_rcpp_approx_expected_value_of_decision_given_perfect_info_fixed_states`, pij, pu_costs, pu_locked_in, alpha, gamma, n_approx_obj_fun_points, budget, gap, states)
}

rcpp_expected_value_of_action <- function(solution, pij, alpha, gamma) {
    .Call(`_surveyvoi_rcpp_expected_value_of_action`, solution, pij, alpha, gamma)
}

rcpp_expected_value_of_decision_given_current_info <- function(pij, pu_costs, pu_locked_in, alpha, gamma, n_approx_obj_fun_points, budget, gap) {
    .Call(`_surveyvoi_rcpp_expected_value_of_decision_given_current_info`, pij, pu_costs, pu_locked_in, alpha, gamma, n_approx_obj_fun_points, budget, gap)
}

rcpp_expected_value_of_decision_given_perfect_info <- function(pij, pu_costs, pu_locked_in, alpha, gamma, n_approx_obj_fun_points, budget, gap) {
    .Call(`_surveyvoi_rcpp_expected_value_of_decision_given_perfect_info`, pij, pu_costs, pu_locked_in, alpha, gamma, n_approx_obj_fun_points, budget, gap)
}

rcpp_expected_value_of_decision_given_survey_scheme <- function(rij, pij, wij, survey_features, survey_sensitivity, survey_specificity, pu_survey_solution, pu_survey_status, pu_survey_costs, pu_purchase_costs, pu_purchase_locked_in, pu_env_data_raw, xgb_parameters, xgb_train_folds, xgb_test_folds, n_xgb_nrounds, obj_fun_alpha, obj_fun_gamma, n_approx_obj_fun_points, total_budget, optim_gap) {
    .Call(`_surveyvoi_rcpp_expected_value_of_decision_given_survey_scheme`, rij, pij, wij, survey_features, survey_sensitivity, survey_specificity, pu_survey_solution, pu_survey_status, pu_survey_costs, pu_purchase_costs, pu_purchase_locked_in, pu_env_data_raw, xgb_parameters, xgb_train_folds, xgb_test_folds, n_xgb_nrounds, obj_fun_alpha, obj_fun_gamma, n_approx_obj_fun_points, total_budget, optim_gap)
}

rcpp_feasible_actions_ilp_matrix <- function(x) {
    .Call(`_surveyvoi_rcpp_feasible_actions_ilp_matrix`, x)
}

rcpp_pmedian_constraint_matrix <- function(x, costs) {
    .Call(`_surveyvoi_rcpp_pmedian_constraint_matrix`, x, costs)
}

rcpp_posterior_probability_matrix <- function(rij, pij, oij, pu_survey_solution, survey_features, survey_sensitivity, survey_specificity, model_sensitivity, model_specificity) {
    .Call(`_surveyvoi_rcpp_posterior_probability_matrix`, rij, pij, oij, pu_survey_solution, survey_features, survey_sensitivity, survey_specificity, model_sensitivity, model_specificity)
}

rcpp_predict_missing_rij_data <- function(rij, wij, pu_env_data_raw, survey_features, pu_model_prediction_idx, xgb_parameters, n_xgb_nrounds, xgb_train_folds, xgb_test_folds) {
    .Call(`_surveyvoi_rcpp_predict_missing_rij_data`, rij, wij, pu_env_data_raw, survey_features, pu_model_prediction_idx, xgb_parameters, n_xgb_nrounds, xgb_train_folds, xgb_test_folds)
}

rcpp_prioritization <- function(rij, pu_costs, pu_locked_in, alpha, gamma, n_approx_obj_fun_points, budget, gap, file_path) {
    .Call(`_surveyvoi_rcpp_prioritization`, rij, pu_costs, pu_locked_in, alpha, gamma, n_approx_obj_fun_points, budget, gap, file_path)
}

rcpp_total_probability_of_positive_result <- function(prior, sensitivity, specificity) {
    .Call(`_surveyvoi_rcpp_total_probability_of_positive_result`, prior, sensitivity, specificity)
}

rcpp_total_probability_of_negative_result <- function(prior, sensitivity, specificity) {
    .Call(`_surveyvoi_rcpp_total_probability_of_negative_result`, prior, sensitivity, specificity)
}

rcpp_probability_of_outcome <- function(oij, total_probability_of_survey_positive, total_probability_of_survey_negative, idx) {
    .Call(`_surveyvoi_rcpp_probability_of_outcome`, oij, total_probability_of_survey_positive, total_probability_of_survey_negative, idx)
}

rcpp_probability_of_state <- function(sij, pij) {
    .Call(`_surveyvoi_rcpp_probability_of_state`, sij, pij)
}

rcpp_total_probability_of_positive_model_result <- function(prior, sensitivity, specificity, feature_outcome_idx) {
    .Call(`_surveyvoi_rcpp_total_probability_of_positive_model_result`, prior, sensitivity, specificity, feature_outcome_idx)
}

rcpp_total_probability_of_negative_model_result <- function(prior, sensitivity, specificity, feature_outcome_idx) {
    .Call(`_surveyvoi_rcpp_total_probability_of_negative_model_result`, prior, sensitivity, specificity, feature_outcome_idx)
}

rcpp_nth_state_sparse <- function(n, idx, matrix) {
    .Call(`_surveyvoi_rcpp_nth_state_sparse`, n, idx, matrix)
}

rcpp_nth_state <- function(n, matrix) {
    .Call(`_surveyvoi_rcpp_nth_state`, n, matrix)
}

rcpp_n_states <- function(n) {
    .Call(`_surveyvoi_rcpp_n_states`, n)
}

rcpp_which_state_sparse <- function(matrix, idx) {
    .Call(`_surveyvoi_rcpp_which_state_sparse`, matrix, idx)
}

rcpp_which_state <- function(matrix) {
    .Call(`_surveyvoi_rcpp_which_state`, matrix)
}

rcpp_sample_k_weighted_nth_states <- function(k, pij) {
    .Call(`_surveyvoi_rcpp_sample_k_weighted_nth_states`, k, pij)
}

rcpp_sample_k_uniform_nth_states <- function(k, pij) {
    .Call(`_surveyvoi_rcpp_sample_k_uniform_nth_states`, k, pij)
}

rcpp_sample_k_uniform_no_replacement_nth_states <- function(k, pij) {
    .Call(`_surveyvoi_rcpp_sample_k_uniform_no_replacement_nth_states`, k, pij)
}

rcpp_fit_xgboost_models_and_assess_performance <- function(rij, wij, pu_env_data_raw, survey_features, xgb_parameters, n_xgb_nrounds, xgb_train_folds, xgb_test_folds) {
    .Call(`_surveyvoi_rcpp_fit_xgboost_models_and_assess_performance`, rij, wij, pu_env_data_raw, survey_features, xgb_parameters, n_xgb_nrounds, xgb_train_folds, xgb_test_folds)
}

rcpp_xgboost <- function(y, train_x_raw, predict_x_raw, xgb_parameters, n_xgb_nrounds) {
    .Call(`_surveyvoi_rcpp_xgboost`, y, train_x_raw, predict_x_raw, xgb_parameters, n_xgb_nrounds)
}

