# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  schedule:
    - cron: 0 0 * * 1 # schedule to run at midnight on Monday each week
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Fedora (devel)

jobs:
  R-CMD-check:
    name: Fedora

    runs-on: ubuntu-latest

    container:
      image: docker://rhub/fedora-clang-devel:latest
      options: --user root
      env:
        _R_REMOTES_NO_ERRORS_FROM_WARNINGS_: true
        _R_CHECK_FORCE_SUGGESTS_: false
        _R_CHECK_TIMINGS_: 10
        _R_CHECK_CRAN_INCOMING_REMOTE_: false
        _R_CHECK_LIMIT_CORES_: true
        _R_CHECK_LICENSE_: true
        OMP_THREAD_LIMIT: 2
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        CI: true

    steps:
      - name: Setup R
        run: |
          echo 'export PATH=$PATH:/opt/R-devel/bin' >> $HOME/.bashrc
          source $HOME/.bashrc
          echo $PATH

      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          dnf install -y \
            mpfr-devel \
            automake \
            fftw-devel \
            gmp-devel \
            openssl-devel \
            zlib-devel \
            pandoc \
            pandoc-citeproc \
            geos-devel \
            make \
            gdal \
            libxml2-devel \
            cmake \
            proj-devel \
            sqlite-devel \
            gdal-devel \
            libicu-devel \
            udunits2-devel \
            coin-or-SYMPHONY-devel \
            git-all

      - name: Install dependencies
        run: |
          options(repos = "https://cloud.r-project.org/")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Session information
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Check
        run: |
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran", "--no-build-vignettes"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash
